### PR TITLE
Small fixes and improvements

### PR DESCRIPTION
**Pull request by Dead2**
-Use git's handling of text files, so it works on all platforms.
-Fix bug that makes tinyint not work with postgresql 10.
-Allow specifying path to pg_config, such as when installing postgresql from the official site, instead of using the distro version.

### CODE REVIEW

**Comment by umitanuki** [comment]
Did you change the line break code from LF to CRLF or something?  Looks like the diff isn't making sense.

**Comment by Dead2** [comment]
No, I changed it from CRLF to LF, and enabled git's text file handling (where git stores files as LF internally, but converts to whatever the current OS expects).

Have a look at the 4 separate commits instead of the whole thing combined.

**Comment by umitanuki** [comment]
ok.  dunno where it got CRLF, but I prefer LF.

**Comment by Dead2** [comment]
Just in case you forgot; remember to roll a new release whenever you feel confident enough about the changes.
I guess most people will be downloading the release tarball :)

**Pull request merged**
